function MitochondriaUI()
    
    global bRenderAVI bPrintTIFs
    
    bRenderAVI = 0;
    bPrintTIFs = 0;
    
    % Create a figure and axes
    f = figure('Visible','on');
    set(f, 'Position', [500 300 800 700]);
    ax = axes('Units', 'Pixels', ...
              'Position', [30, 55, 400, 300], ...
              'Tag', 'imageAxis', ...
              'Parent', f, ...
              'Color', 'white');
    set(gca,'ytick',[]); 
    set(gca,'xtick',[]);
    set(gca, 'XColor', 'w');
    set(gca, 'YColor', 'w');
    
    % UI Title
    UITitle_Text = uicontrol('Style', 'Text',...
                    'String', 'Mitochondria Analysis Tool', ...
                    'BackgroundColor', [255/255, 255/255, 102/255], ...
                    'FontWeight', 'bold', ...
                    'FontSize', 15, ...
                    'Position', [150 655 500 30]);

    ProgressString_Text = uicontrol('Style', 'Text',...
                'BackgroundColor', [200/255, 200/255, 200/255], ...
                'String', 'Configure your experiment settings.', ...
                'HorizontalAlignment', 'right', ...
                'Tag', 'ProgressString', ...
                'FontSize', 8, ...
                'Position', [480 0 321 20]); %[2 0 300 20]
            
     MaxTime_Text = uicontrol('Style', 'Text', ...
                'String', 'Number of Total Frames: ', ...
                'HorizontalAlignment', 'left', ...
                'Tag', 'MaxTimes', ...
                'FontSize', 10', ...
                'Position', [40 5 200 30]); %[465 5 200 30]
            
      MaxTime_Edit = uicontrol('Style', 'edit', ...
                'String', '101', ...
                'HorizontalAlignment', 'center', ...
                'Tag', 'MaxTime', ...
                'FontSize', 10', ...
                'Position', [190 10 40 30]); %[615 10 40 30]
                
 % CONDITION 1 --------------------------------------------------------
    Cond1Title_Text = uicontrol('Style', 'Text',...
                        'String', 'CONDITION 1', ...
                        'FontSize', 10, ...
                        'Position', [180 620 100 25]);
    
    Cond1Label_Text = uicontrol('Style', 'Text',...
                            'String', 'Condition Label', ...
                            'HorizontalAlignment', 'left', ...
                            'FontSize', 10, ...
                            'Position', [15 586 100 30]);
                        
    Cond1Label_Edit = uicontrol('Style', 'edit',...
                            'FontSize', 10, ...
                            'Tag', 'Cond1Label', ...
                            'Position', [115 595 70 25]);
                        
    Cond1Path_Text = uicontrol('Style', 'Text',...
                            'String', 'Image Folder Paths', ...
                            'FontSize', 8, ...
                            'FontAngle', 'italic', ...
                            'Position', [180 564 100 30]);
    
       % [Condition 1, Experiment 1]
    Cond1E1_Text = uicontrol('Style', 'Text',...
                            'String', 'Experiment 1', ...
                            'FontSize', 9.5, ...
                            'Position', [20 545 90 30]);
    Cond1E1_Edit = uicontrol('Style', 'Edit',...
                            'Tag', 'C1E1Dir', ...
                            'Position', [115 557 250 18]); 
    Cond1E1_Button = uicontrol('Style', 'pushbutton',...
                            'String', '...', ...
                            'FontSize', 9.5, ...
                            'Position', [365 556 20 20], ...
                            'Callback', {@expFolderPath, Cond1E1_Edit});
    
        % [Condition 1, Experiment 2]
    Cond1E2_Text = uicontrol('Style', 'Text',...
                            'String', 'Experiment 2', ...
                            'FontSize', 9.5, ...
                            'Position', [20 515 90 30]);
    Cond1E2_Edit = uicontrol('Style', 'Edit',...
                            'Tag', 'C1E2Dir', ...
                            'Position', [115 527 250 18]); 
    Cond1E2_Button = uicontrol('Style', 'pushbutton',...
                            'String', '...', ...
                            'FontSize', 9.5, ...
                            'Position', [365 526 20 20], ...
                            'Callback', {@expFolderPath, Cond1E2_Edit});
                        
        % [Condition 1, Experiment 3]
    Cond1E3_Text = uicontrol('Style', 'Text',...
                            'String', 'Experiment 3', ...
                            'FontSize', 9.5, ...
                            'Position', [20 485 90 30]);
    Cond1E3_Edit = uicontrol('Style', 'Edit',...
                            'Tag', 'C1E3Dir', ...
                            'Position', [115 497 250 18]); 
    Cond1E3_Button = uicontrol('Style', 'pushbutton',...
                            'String', '...', ...
                            'FontSize', 9.5, ...
                            'Position', [365 496 20 20], ...
                            'Callback', {@expFolderPath, Cond1E3_Edit});
                        
        % [Condition 1, Experiment 4]
    Cond1E4_Text = uicontrol('Style', 'Text',...
                            'String', 'Experiment 4', ...
                            'FontSize', 9.5, ...
                            'Position', [20 455 90 30]);
    Cond1E4_Edit = uicontrol('Style', 'Edit',...
                            'Tag', 'C1E4Dir', ...
                            'Position', [115 467 250 18]); 
    Cond1E4_Button = uicontrol('Style', 'pushbutton',...
                            'String', '...', ...
                            'FontSize', 9.5, ...
                            'Position', [365 466 20 20], ...
                            'Callback', {@expFolderPath, Cond1E4_Edit});
                        
        % [Condition 1, Experiment 5]
    Cond1E5_Text = uicontrol('Style', 'Text',...
                            'String', 'Experiment 5', ...
                            'FontSize', 9.5, ...
                            'Position', [20 425 90 30]);
    Cond1E5_Edit = uicontrol('Style', 'Edit',...
                            'Tag', 'C1E5Dir', ...
                            'Position', [115 437 250 18]); 
    Cond1E5_Button = uicontrol('Style', 'pushbutton',...
                            'String', '...', ...
                            'FontSize', 9.5, ...
                            'Position', [365 436 20 20], ...
                            'Callback', {@expFolderPath, Cond1E5_Edit});
                        
 % CONDITION 2 --------------------------------------------------------
    Cond2Title_Text = uicontrol('Style', 'Text',...
                        'String', 'CONDITION 2', ...
                        'FontSize', 10, ...
                        'Position', [560 620 100 25]);
    
    Cond2Label_Text = uicontrol('Style', 'Text',...
                            'String', 'Condition Label', ...
                            'HorizontalAlignment', 'left', ...
                            'FontSize', 10, ...
                            'Position', [395 586 100 30]);
                        
    Cond2Label_Edit = uicontrol('Style', 'edit',...
                            'Tag', 'Cond2Label', ...
                            'FontSize', 10, ...
                            'Position', [495 595 70 25]);
                        
    Cond2Path_Text = uicontrol('Style', 'Text',...
                            'String', 'Image Folder Paths', ...
                            'FontSize', 8, ...
                            'FontAngle', 'italic', ...
                            'Position', [560 564 100 30]);
    
       % [Condition 2, Experiment 1]
    Cond2E1_Text = uicontrol('Style', 'Text',...
                            'String', 'Experiment 1', ...
                            'FontSize', 9.5, ...
                            'Position', [400 545 90 30]);
    Cond2E1_Edit = uicontrol('Style', 'Edit',...
                            'Tag', 'C2E1Dir', ...
                            'Position', [495 557 250 18]); 
    Cond2E1_Button = uicontrol('Style', 'pushbutton',...
                            'String', '...', ...
                            'FontSize', 9.5, ...
                            'Position', [745 556 20 20], ...
                            'Callback', {@expFolderPath, Cond2E1_Edit});
    
        % [Condition 2, Experiment 2]
    Cond2E2_Text = uicontrol('Style', 'Text',...
                            'String', 'Experiment 2', ...
                            'FontSize', 9.5, ...
                            'Position', [400 515 90 30]);
    Cond2E2_Edit = uicontrol('Style', 'Edit',...
                            'Tag', 'C2E2Dir', ...
                            'Position', [495 527 250 18]); 
    Cond2E2_Button = uicontrol('Style', 'pushbutton',...
                            'String', '...', ...
                            'FontSize', 9.5, ...
                            'Position', [745 526 20 20], ...
                            'Callback', {@expFolderPath, Cond2E2_Edit});
                        
        % [Condition 2, Experiment 3]
    Cond2E3_Text = uicontrol('Style', 'Text',...
                            'String', 'Experiment 3', ...
                            'FontSize', 9.5, ...
                            'Position', [400 485 90 30]);
    Cond2E3_Edit = uicontrol('Style', 'Edit',...
                            'Tag', 'C2E3Dir', ...
                            'Position', [495 497 250 18]); 
    Cond2E3_Button = uicontrol('Style', 'pushbutton',...
                            'String', '...', ...
                            'FontSize', 9.5, ...
                            'Position', [745 496 20 20], ...
                            'Callback', {@expFolderPath, Cond2E3_Edit});
                        
        % [Condition 2, Experiment 4]
    Cond2E4_Text = uicontrol('Style', 'Text',...
                            'String', 'Experiment 4', ...
                            'FontSize', 9.5, ...
                            'Position', [400 455 90 30]);
    Cond2E4_Edit = uicontrol('Style', 'Edit',...
                            'Tag', 'C2E4Dir', ...
                            'Position', [495 467 250 18]); 
    Cond2E4_Button = uicontrol('Style', 'pushbutton',...
                            'String', '...', ...
                            'FontSize', 9.5, ...
                            'Position', [745 466 20 20], ...
                            'Callback', {@expFolderPath, Cond2E4_Edit});
                        
        % [Condition 2, Experiment 5]
    Cond2E5_Text = uicontrol('Style', 'Text',...
                            'String', 'Experiment 5', ...
                            'FontSize', 9.5, ...
                            'Position', [400 425 90 30]);
    Cond2E5_Edit = uicontrol('Style', 'Edit',...
                            'Tag', 'C2E5Dir', ...
                            'Position', [495 437 250 18]); 
    Cond2E5_Button = uicontrol('Style', 'pushbutton',...
                            'String', '...', ...
                            'FontSize', 9.5, ...
                            'Position', [745 436 20 20], ...
                            'Callback', {@expFolderPath, Cond2E5_Edit});
                        
 % TOGGLE OUTPUTS -------------------------------------------------------
    ToggleTitle_Text = uicontrol('Style', 'Text',...
                            'String', 'Toggle outputs...', ...
                            'FontSize', 10, ...
                            'Position', [30 370 100 30]);
                        
    SavePath_Text = uicontrol('Style', 'Text',...
                            'String', 'Save Folder Path', ...
                            'FontSize', 8.5, ...
                            'FontAngle', 'italic', ...
                            'Visible', 'off', ...
                            'Position', [455 352 200 30]);
    SavePath_Edit = uicontrol('Style', 'Edit',...
                            'Visible', 'off', ...
                            'Tag', 'SaveDir', ...
                            'Position', [450 382 200 18]); 
    SavePath_Button = uicontrol('Style', 'pushbutton',...
                            'String', '...', ...
                            'FontSize', 9.5, ...
                            'Visible', 'off', ...
                            'Position', [650 381 20 20], ...
                            'Callback', {@expFolderPath, SavePath_Edit});    
    
    RenderAVI_Toggle = uicontrol('Style', 'togglebutton', ...
                            'String', 'Render Movie', ...
                            'FontSize', 9.5, ...
                            'FontWeight', 'bold', ...
                            'Tag', 'RenderAVI', ...
                            'Position', [150, 375, 100, 30], ...
                            'Callback', {@savePathVisibility, SavePath_Edit, SavePath_Text, SavePath_Button});
    
    PrintTIFs_Toggle = uicontrol('Style', 'togglebutton', ...
                            'String', 'Print TIFs', ...
                            'FontSize', 9.5, ...
                            'Tag', 'PrintTIF', ...
                            'FontWeight', 'bold', ...
                            'Position', [300, 375, 100, 30], ...
                            'Callback', {@savePathVisibility, SavePath_Edit, SavePath_Text, SavePath_Button});         
 
 % ANALYSIS OPTIONS -------------------------------------------------------
    
    % [Fission and Fusion]
    FisFus_Text = uicontrol('Style', 'text', ...
                            'String', 'Fission and Fusion Analysis', ...
                            'HorizontalAlignment', 'left', ...
                            'FontSize', 10, ...
                            'Position', [490 307 170 20]);
                        
    FisFusLifetime_Text = uicontrol('Style', 'text', ...
                            'String', 'Minimum Number of Frames to Qualify as Mitochondria: ', ...
                            'FontSize', 8, ...
                            'HorizontalAlignment', 'left', ...
                            'Visible', 'off', ...
                            'Position', [505 265 190 40]);
    FisFusLifetime_Edit = uicontrol('Style', 'Edit', ...
                            'String', 5, ...
                            'FontSize', 8, ...
                            'Tag', 'FisFusLifetime', ...
                            'Visible', 'off', ...
                            'Position', [695 280 20 20]);

    FisFusDXY_Text = uicontrol('Style', 'text', ...
                            'String', 'Max distance between mitochondria frame-to-frame (in pixels): ', ...
                            'FontSize', 8, ...
                            'HorizontalAlignment', 'left', ...
                            'Visible', 'off', ...
                            'Position', [505 230 190 40]);
    FisFusDXY_Edit = uicontrol('Style', 'Edit', ...
                            'String', 20, ...
                            'FontSize', 8, ...
                            'Tag', 'FisFusDXY', ...
                            'Visible', 'off', ...
                            'Position', [695 245 50 20]);
    FisFus_CheckBox = uicontrol('Style', 'checkbox', ...
                        'Position', [465 310 20 20], ...
                        'Tag', 'FisFusCheck', ...
                        'Callback', {@changeVisibility, FisFusLifetime_Text, FisFusLifetime_Edit, ...
                            FisFusDXY_Text, FisFusDXY_Edit});
                        
    % [Mitochondria Velocity]
    MitoVel_Text = uicontrol('Style', 'text', ...
                            'HorizontalAlignment', 'left', ...
                            'String', 'Velocity Analysis', ...
                            'FontSize', 10, ...
                            'Position', [490 210 170 20]);
                        
    MitoVelLifetime_Text = uicontrol('Style', 'text', ...
                            'String', 'Minimum Number of Frames to Qualify as Mitochondria: ', ...
                            'FontSize', 8, ...
                            'HorizontalAlignment', 'left', ...
                            'Visible', 'off', ...
                            'Position', [505 165 190 40]);
    MitoVelLifetime_Edit = uicontrol('Style', 'Edit', ...
                            'String', 5, ...
                            'FontSize', 8, ...
                            'Visible', 'off', ...
                            'Tag', 'MitoVelocityLifetime', ...
                            'Position', [695 180 20 20]);

    MitoVelTotTime_Text = uicontrol('Style', 'text', ...
                            'String', 'Total imaging time (in seconds): ', ...
                            'FontSize', 8, ...
                            'HorizontalAlignment', 'left', ...
                            'Visible', 'off', ...
                            'Position', [505 130 190 40]);
    MitoVelTotTime_Edit = uicontrol('Style', 'Edit', ...
                            'String', 960, ...
                            'FontSize', 8, ...
                            'Visible', 'off', ...
                            'Tag', 'MitoVelocityTotalTime', ...
                            'Position', [660 152 50 20]);
    
    MitoVelPixelRes_Text = uicontrol('Style', 'text', ...
                            'String', 'Pixel Resolution: ', ...
                            'FontSize', 8, ...
                            'HorizontalAlignment', 'left', ...
                            'Visible', 'off', ...
                            'Position', [505 123 190 20]);
                        
    MitoVelPixelResX_Text = uicontrol('Style', 'text', ...
                            'String', 'X', ...
                            'FontSize', 8, ...
                            'HorizontalAlignment', 'left', ...
                            'Visible', 'off', ...
                            'Position', [590 123 190 20]);
                        
    MitoVelPixelResX_Edit = uicontrol('Style', 'Edit', ...
                            'String', '', ...
                            'FontSize', 8, ...
                            'Visible', 'off', ...
                            'Tag', 'MitoVelocityResX', ...
                            'Position', [600 126 30 20]);
                        
    MitoVelPixelResY_Text = uicontrol('Style', 'text', ...
                            'String', 'Y', ...
                            'FontSize', 8, ...
                            'HorizontalAlignment', 'left', ...
                            'Visible', 'off', ...
                            'Position', [645 123 190 20]);
                        
    MitoVelPixelResY_Edit = uicontrol('Style', 'Edit', ...
                            'String', '', ...
                            'FontSize', 8, ...
                            'Visible', 'off', ...
                            'Tag', 'MitoVelocityResY', ...
                            'Position', [655 126 30 20]);
                        
    MitoVelPixelResZ_Text = uicontrol('Style', 'text', ...
                            'String', 'Z', ...
                            'FontSize', 8, ...
                            'HorizontalAlignment', 'left', ...
                            'Visible', 'off', ...
                            'Position', [700 123 190 20]);
                        
    MitoVelPixelResZ_Edit = uicontrol('Style', 'Edit', ...
                            'String', '', ...
                            'FontSize', 8, ...
                            'Visible', 'off', ...
                            'Tag', 'MitoVelocityResZ', ...
                            'Position', [710 126 30 20]);
                        
    MitoVel_CheckBox = uicontrol('Style', 'checkbox', ...
                            'Position', [465 210 20 20], ...
                            'Tag', 'MitoVelocityCheck', ...
                            'Callback', {@changeVisibility, MitoVelLifetime_Text, MitoVelLifetime_Edit, ...
                                MitoVelTotTime_Text, MitoVelTotTime_Edit, MitoVelPixelRes_Text, ...
                                MitoVelPixelResX_Text, MitoVelPixelResX_Edit, ...
                                MitoVelPixelResY_Text, MitoVelPixelResY_Edit, ...
                                MitoVelPixelResZ_Text, MitoVelPixelResZ_Edit});                          
                            
    % [Mitochondria Spatial Analysis]
    MitoSpatial_Text = uicontrol('Style', 'text', ...
                            'HorizontalAlignment', 'left', ...
                            'String', 'Spatiotemporal Distribution Analysis', ...
                            'FontSize', 10, ...
                            'Position', [490 93 250 20]);
    MitoSpatial_CheckBox = uicontrol('Style', 'checkbox', ...
                            'Tag', 'MitoSpatialCheck', ...
                            'Position', [465 95 20 20]);
    
 % START ANALYSIS ---------------------------------------------------------
    
    Start_Button = uicontrol('Style', 'pushbutton',...
                    'String', 'Start', ...
                    'FontWeight', 'bold', ...
                    'FontSize', 9.5, ...
                    'Position', [375 10  50 30], ... 
                    'Callback', {@startMitoAnalysis, f});
end

function expFolderPath(src, evnt, updateStr)
inDir = uigetdir;
set(updateStr, 'String', inDir);
set(src,'UserData',inDir);
end

function savePathVisibility(src, evnt, varargin)

global bRenderAVI bPrintTIFs

if strcmp(src.Tag, 'PrintTIF')
    bPrintTIFs = src.Value;
elseif strcmp(src.Tag, 'RenderAVI')
    bRenderAVI = src.Value;
end

if nargin-2 > 0
    if any([bPrintTIFs, bRenderAVI]==1)
        for i = 1:nargin-2
            set(varargin{i}, 'Visible', 'on');
        end
    else
        for i = 1:nargin-2
            set(varargin{i}, 'Visible', 'off');
        end
    end
end

end

function changeVisibility(src, evnt, varargin)

if nargin-2 > 0
    if src.Value
        for i = 1:nargin-2
            set(varargin{i}, 'Visible', 'on');
        end
    else
        for i = 1:nargin-2
            set(varargin{i}, 'Visible', 'off');
        end
    end
end

end

function startMitoAnalysis(src, evnt, fig)
    gui0 = guihandles(fig);
    
    MitoAnalysisVar = struct('ImageAxesHandle',     gui0.imageAxis, ...
                            'ProgressStringHandle', gui0.ProgressString, ...
                            'MaxTime',             gui0.MaxTime.String, ...
                            'Cond1_Label',          gui0.Cond1Label.String, ...
                            'Cond2_Label',          gui0.Cond2Label.String, ...
                            'Cond1_ExpDir',         {{gui0.C1E1Dir.String; ...
                                                        gui0.C1E2Dir.String; ...
                                                        gui0.C1E3Dir.String; ...
                                                        gui0.C1E4Dir.String; ...
                                                        gui0.C1E5Dir.String}}, ...
                            'Cond2_ExpDir',         {{gui0.C2E1Dir.String; ...
                                                        gui0.C2E2Dir.String; ...
                                                        gui0.C2E3Dir.String; ...
                                                        gui0.C2E4Dir.String; ...
                                                        gui0.C2E5Dir.String}}, ...
                            'bRenderMov',           gui0.RenderAVI.Value, ...
                            'bPrintTIFs',           gui0.PrintTIF.Value, ...
                            'SaveToPath',           gui0.SaveDir.String, ...
                            'bFisFusAnalysis',      gui0.FisFusCheck.Value, ...
                            'FisFus_LifeThresh',    str2num(gui0.FisFusLifetime.String), ...
                            'FisFus_DXYmax',        str2num(gui0.FisFusDXY.String), ...
                            'bVelocityAnalysis',    gui0.MitoVelocityCheck.Value, ...
                            'Velocity_TotalTime',   str2num(gui0.MitoVelocityTotalTime.String), ...
                            'Velocity_LifeThresh',  str2num(gui0.MitoVelocityLifetime.String), ...
                            'Velocity_PixelRes',    [str2num(gui0.MitoVelocityResX.String), ....
                                                        str2num(gui0.MitoVelocityResY.String), ...
                                                        str2num(gui0.MitoVelocityResZ.String)], ...
                            'bSpatialAnalysis',     gui0.MitoSpatialCheck.Value);
                        
    if MitoAnalysisVar.bFisFusAnalysis == 0
        MitoAnalysisVar.FisFus_LifeThresh = [];
        MitoAnalysisVar.FisFus_DXYmax = [];
    end
    
    if MitoAnalysisVar.bVelocityAnalysis == 0
        MitoAnalysisVar.Velocity_TotalTime = [];
        MitoAnalysisVar.Velocity_LifeThresh = [];
    end
    
    RunMitochondriaAnalysis(MitoAnalysisVar);
end